### PR TITLE
Do not hardcode python install location

### PR DESCRIPTION
**Pull request by KonstantinSchubert**
:)

### CODE REVIEW

**Comment by toobaz** [comment]
The change is trivial but the reasons for it are not (to me). Is it related to virtualenv?

**Comment by KonstantinSchubert** [comment]
I'm not sure about virtual environments.

But for any system where python is not installed in /usr/bin/python, the
script will work only after the pull request.

Pietro Battiston notifications@github.com schrieb am Sa., 9. Juli 2016
17:36:

**Comment by ibab** [comment]
Hi, I discussed this earlier with @KonstantinSchubert, so maybe I should add an explanation as well:
The script didn't work on my system, because I've installed the dependencies into my [anaconda](https://www.continuum.io/downloads) environment at `~/.anaconda` with Python at `~/.anaconda/bin/python`.
When running the script, it picks up the python at `/usr/bin/python`, which doesn't have access to the `nbformat` dependency on my system.
The solution is to dynamically select the currently active `python` by using `/usr/bin/env`.
Here's an explanation of how this works: https://askubuntu.com/questions/716280/why-do-some-python-scripts-begin-with-usr-bin-env-python

**Comment by toobaz** [comment]
Right, makes sense, jupyter stuff will often not be available to the default python. Thanks!

**Pull request merged**
