### PR TITLE
cleanup widgets

### PR DESCRIPTION
**Pull request by anselmevignon**

### CODE REVIEW

**Comment by toobaz** [comment]
Thank you very much! Just one clarification: is there a particular reason why you think that

```
sheet.metadata.widgets = {}
```

is better than

```
del sheet.metadata.widgets
```

? Not that this is _soo_ relevant, but in this second case, the presence of the ipywidgets should go completely unnoticed, which might be good.

**Comment by anselmevignon** [comment]
Makes sense indeed.

Let me check for unintended consequences on Monday,  il push the change
then.
Le 28 mai 2016 11:20, "Pietro Battiston" notifications@github.com a
écrit :

**Comment by anselmevignon** [comment]
done ! thanks for the review

**Comment by toobaz** [comment]
Thanks to you!

**Pull request merged**
